### PR TITLE
Fixed code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/maestral/issues/). This PR fixes a few of them.

## Summary of Fixes

- Remove reimported module
- Simplified the if statements
- Refactor the comparison involving `not`
- Added .deepsource.toml to fix bug risk

## Type of change

- [✔] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [✔] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by SamSchott — CHANGES_REQUESTED** [review]
@ankitdobhal, thanks for PR. From a brief look, the proposed changes are cosmetic and tend to priorities brevity over legibility. They also don't conform the "black" code style which is enforced in this project, therefore the failing checks.

The code quality analyses raises some valid issues but I am sceptical about the automatic changes. At the very least, they need to conform to the enforced code style of the repo.

**Comment by ankitdobhal** [comment]
> @ankitdobhal, thanks for PR. From a brief look, the proposed changes are cosmetic and tend to priorities brevity over legibility. They also don't conform the "black" code style which is enforced in this project, therefore the failing checks.
> 
> The code quality analyses raises some valid issues but I am sceptical about the automatic changes. At the very least, they need to conform to the enforced code style of the repo.

Thanks @SamSchott for response. I have updated the changes in PR.
As far concerning about  "black" code style which is enforced in this project, So [DeepSource](https://deepsource.io/) can automatically run **black**, **isort** **autopep8** in the **PRs**, with the help of [code auto-formatters](https://deepsource.io/docs/transformer/) .
You just need to add the transformer inside the .toml file for automatic code styles , with the help of [docs](https://deepsource.io/docs/transformer/).

**Comment by ankitdobhal** [comment]
> > @ankitdobhal, thanks for PR. From a brief look, the proposed changes are cosmetic and tend to priorities brevity over legibility. They also don't conform the "black" code style which is enforced in this project, therefore the failing checks.
> > The code quality analyses raises some valid issues but I am sceptical about the automatic changes. At the very least, they need to conform to the enforced code style of the repo.
> 
> Thanks @SamSchott for response. I have updated the changes in PR and fixes the checks.
> As far concerning about "black" code style which is enforced in this project, So [DeepSource](https://deepsource.io/) can automatically run **black**, **isort** **autopep8** in the **PRs**, with the help of [code auto-formatters](https://deepsource.io/docs/transformer/) .
> You just need to add the transformer inside the .toml file for automatic code styles , with the help of [docs](https://deepsource.io/docs/transformer/) after activating it in repo.
> 
> Thanks !

@SamSchott KIdnly review the updated PR.

**Comment by SamSchott** [comment]
@ankitdobhal, thanks for the changes! I'll need to have a more detailed look at deepsource next week but this is generally looking quite useful to me.

**Comment by ankitdobhal** [comment]
> @ankitdobhal, thanks for the changes! I'll need to have a more detailed look at deepsource next week but this is generally looking quite useful to me.

Sure @SamSchott .
Let me share some steps with you to activate [DeepSource](https://deepsource.io/) . 

Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 

To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:

- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
> Note: This PR already have .deepsource.toml file so after merging you don't to create this one.
- Activate analysis [here](https://deepsource.io/gh/SamSchott/maestral/issues).

**Comment by ankitdobhal** [comment]
> @ankitdobhal, thanks for the changes! I'll need to have a more detailed look at deepsource next week but this is generally looking quite useful to me.

@SamSchott Sorry to bother you again.
But kindly review the fixes and merge them if you find it useful.
Thanks.

**Review by SamSchott — APPROVED** [review]
This looks good to me, thanks!

**Pull request merged**
