### PR TITLE
ISSUE-199: systemd detection error handling.

### PR DESCRIPTION
**Pull request by aries1980**
See: https://github.com/SamSchott/maestral/issues/199

### CODE REVIEW

**Comment by SamSchott** [comment]
Thanks for spotting this and for the PR.

Would it make sense to be more specific in error handling, for instance catching `CalledProcessError` for invalid options and `FileNotFoundError` if the `ps` program is not on the path?

On a side note, do you know of a better way for detecting if a platform uses systemd? Checking the process with PID 1 was the best I could come up with.

**Comment by aries1980** [comment]
I am not sure if it is the app where we should handle the platform-specific stuff. E.g. when we build a Fedora/Redhat, Ubuntu, Debian, etc packages there we should provide a .service systemd unit file or upstart, etc. Otherwise it is always be flakey and the user might not want autostart. If they want, just do a `systemctl enable maestral`, `service maestral enable` or whatever their system uses.

**Comment by SamSchott** [comment]
I agree that this is fundamentally a very platform-specific issue.

Currently, the main installation path for users is a `pip install` which has very poor support for installing additional files into system directories and the target audience often is not comfortable setting up a systemd service manually. This was my motivation for providing the `maestral autostart` CLI command and the corresponding module.

In the medium term, it would like to at least move any GUI specific autostart functionality to the `maestral-cocoa` and `maestral-qt` packages. This will remove annoying if-else clauses.

Autostart is disabled by default. However, v1.2.1 includes code to update any existing systemd service files after the upgrade. This requires creating an `AutoStart` instance, which fails as described in #199 and reveals an issue which I previously did not notice.

**Review by SamSchott — COMMENTED** [review]
Can you make the exception handling a bit more specific? Then I'll merge.

**Comment by SamSchott** [comment]
I'm closing this since it's superseded by and incorporated in #210 which refactors and simplifies the autostart module. Thanks for flagging the issue and for the PR!

**Pull request closed without merging**
